### ISSUE TITLE
F0 Suppprt

### ISSUE THREAD

**Issue by chadmbrown** [BossHobby/QUICKSILVER#99]
I was thinking this project could be used to continue innovation for the indoor brushed whoop space. The Hummingbird with Mockingbird settings is hard to beat for indoor flying. Any plans for this project to service that market?

**Comment by bkleiner** [comment]
This Project started out as a port of (NFE_Silverware)[https://github.com/NotFastEnuf/NFE_Silverware] to F4, however support for F0 was eventually dropped because of the limitations of the chip and the declining interest. https://github.com/BossHobby/QUICKSILVER/commit/c4ca102856e284d05d5781e01292757d73014b18

Brushed support is very much still present, in fact a lot of the early development was done on brushed, however in recent years, probably also because of declining interest, getting parts for it has become increasingly difficult.

At this point i don't foresee a future where more time is invested into Brushed and/or F0, this is really where we come from and not where we are headed.
